%YAML:1.0
# something not used

T: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ 3., 1., 5. ]
barrierBase: 100
coolingRateSA: 0.1
coreNumberAva: 5
debugMode: 0 # 1 means NLP, 2 means SA, 0 means initial
deltaInitialDogleg: 1e5
weightDDL_factor: 1.0
deltaOptimizer: 1e-1
exactJacobian: 0
initialLambda: 1e0
lowerLambda: 1e-15
makespanWeight: 1e-5
noiseModelSigma: 1
AcceptSchedulError: 1e0
optimizerType: 2 # 1 means dogleg, 2 means LM
overlapMode: 1
parallelFactor: 0.4
punishmentInBarrier: 1e2
randomInitialize: 0
readTaskMode: orig
withAddedSensorFusionError: 1
ElimnateLoop_Max: 50
zeroJacobianDetectTol: 1e-7
maxIterations: 100
moreElimination: 0
weightPrior_factor: 0
initializeMethod: 2
timeScaleFactor: 1e2
stepJacobianIteration: 1.5
maxJacobianIteration: 25
priorityMode: RM
relativeErrorTolerance: 1e-5
runMode: compare
SA_iteration: 100000
sensorFusionTolerance: 50
FreshTol: 50
temperatureSA: 100000000
testDataSetName: test_n5_v40
tightEliminate: 0
toleranceEliminator: 1
upperLambda: 1e60
weightLogBarrier: -1.0
setUseFixedLambdaFactor: 1
batchTestMethod: 1 # 1 means NLP, 2 means SA, 0 means initial
numericalJaobian: 0
TaskSetType: 1 # 1 means total random, 2 means automobile tasksets