%YAML:1.0

# optimization seettings
batchTestMethod: 1 # 0 means initial, 1 means proposed optimization, 2 means Verucchi20, 3 means NLP, SA is not considered
TotalMethodUnderComparison: 4
testDataSetName: test_n3_v8
debugMode: 0
doScheduleOptimization: 1
#*************************************************************
# Get away from local optimal setting
RandomAccept: 0 # chance to take a possibly better solution
#*************************************************************


# task-set settings
coreNumberAva: 2
processorAssignmentMode: 1 # 0 means using given processor assignment, 1 means using deciding by the scheduling algorithm
priorityMode: orig
# task set generator settings
parallelFactor: 0.4 # percentage of edges in generated dag
TaskSetType: 1 # 1 means total random, 2 means automobile tasksets
timeScaleFactor: 1e0 # used to scale minimum period to 1 or larger, as currently only support integer periods

#*************************************************************
# factors to be included
weightDDL_factor: 1e0
weightDAG_factor: 0
weightSF_factor: 1
RtdaWeight: 1e0
DataAgeThreshold: 1e3
ReactionTimeThreshold: 1e3
NumCauseEffectChain: 1
whether_shuffle_CE_chain: 0
makespanWeight: 0
sensorFusionTolerance: 500000
FreshTol: 50000
withAddedSensorFusionError: 1
#*************************************************************

# used in SA
coolingRateSA: 0.1
randomInitialize: 0
temperatureSA: 100000000
SA_iteration: 100000
#*************************************************************
# Verucchi20 settings
kVerucchiTimeLimit: 5 # seconds, -1 means unlimited time
kVerucchiReactionCost: 15.0
kVerucchiMaxReaction: 400000.0
kVerucchiDataAgeCost: 15.0
kVerucchiMaxDataAge: 400000.0
kVerucchiCoreCost: 50.0
#*************************************************************

# Cplex settings
kCplexInequalityThreshold: 1e-3
#*************************************************************





#*************************************************************
# Used only in old optimization system
initializeMethod: 5
recordActionValue: 0
PrintOutput: 1
PrintInitial: 1
numericalJaobian: 0
exactJacobian: 0
deltaOptimizer: 1e0
optimizerType: 2 # 1 means dogleg, 2 means LM
runMode: compare
AcceptSchedulError: 1e-2


# Get away from local optimal setting
whetherRandomNoiseModelSigma: 0
RandomDrawWeightMaxLoop: 8 # must be >=1
ResetInnerWeightLoopMax: 5 # must be >=1
ResetRandomWeightThreshold: 5e-3
RoundingThreshold: 1e-3

# optimizer settings
whether_ls: 1
deltaInitialDogleg: 1e5
initialLambda: 1e-6
lowerLambda: 1e-20
upperLambda: 1e50
# verbosityLM: "SILENCE"
verbosityLM: "SUMMARY"
# verbosityLM: "TRYDELTA"
relativeErrorTolerance: 1e-5
setUseFixedLambdaFactor: 1
setDiagonalDamping: 0
maxIterations: 10000


# Elimination settings
MaxEliminateDetectIterations: 25
stepJacobianIteration: 1.5
toleranceEliminator: 1
tightEliminate: 0
zeroJacobianDetectTol: 1e-4


# no need to adjust
noiseModelSigma: 1
saveGraph: 0

# not used
barrierBase: 100
punishmentInBarrier: 1e2
weightLogBarrier: -1.0
#*************************************************************