%YAML:1.0

# optimization seettings
batchTestMethod: 1 # 1 means NLP, 2 means SA, 0 means initial, 3 means Verucchi20
testDataSetName: test_n5_v68
AcceptSchedulError: 1e-2
debugMode: 0
recordActionValue: 1
runMode: compare
initializeMethod: 2
optimizerType: 2 # 1 means dogleg, 2 means LM

deltaOptimizer: 1e0
exactJacobian: 0
numericalJaobian: 0
PrintOutput: 1
PrintInitial: 0
#*************************************************************

# Elimination settings
MaxEliminateDetectIterations: 25
stepJacobianIteration: 1.5
toleranceEliminator: 1
tightEliminate: 0
zeroJacobianDetectTol: 1e-4
#*************************************************************

# Get away from local optimal setting
whetherRandomNoiseModelSigma: 1
RandomDrawWeightMaxLoop: 10
ResetInnerWeightLoopMax: 10
ResetRandomWeightThreshold: 5e-3
#*************************************************************

# optimizer settings
deltaInitialDogleg: 1e5
initialLambda: 1e0
lowerLambda: 1e-60
upperLambda: 1e50
verbosityLM: "SILENCE"
# verbosityLM: "SUMMARY"
# verbosityLM: "TRYDELTA"
relativeErrorTolerance: 1e-5
setUseFixedLambdaFactor: 1
setDiagonalDamping: 0
maxIterations: 10000
#*************************************************************

# factors to be included
weightDDL_factor: 2.5
weightDAG_factor: 1.8
makespanWeight: 0
weightPrior_factor: 0
sensorFusionTolerance: 500000
FreshTol: 50000
withAddedSensorFusionError: 1
#*************************************************************

# task-set settings
coreNumberAva: 1
parallelFactor: 0.4
readTaskMode: orig
TaskSetType: 1 # 1 means total random, 2 means automobile tasksets
timeScaleFactor: 1e0
priorityMode: RM
#*************************************************************

# used in SA
coolingRateSA: 0.1
randomInitialize: 0
temperatureSA: 100000000
SA_iteration: 100000
#*************************************************************


# no need to adjust
noiseModelSigma: 1
saveGraph: 0
#*************************************************************

# not used
barrierBase: 100
punishmentInBarrier: 1e2
weightLogBarrier: -1.0
T: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ 3., 1., 5. ]
#*************************************************************