%YAML:1.0
# something not used


barrierBase: 100
coolingRateSA: 0.99
debugMode: 1
deltaInitialDogleg: 1e5
weightDDL_factor: 1.0
deltaOptimizer: 1e-1
exactJacobian: 0
initialLambda: 1e0
lowerLambda: 1e-15
makespanWeight: 0
noiseModelSigma: 1
AcceptSchedulError: 1e-1
optimizerType: 2 # 1 means dogleg, 2 means LM
overlapMode: 1
parallelFactor: 0.4
punishmentInBarrier: 1e2
randomInitialize: 0
readTaskMode: orig
withAddedSensorFusionError: 1
zeroJacobianDetectTol: 1e-7
maxIterations: 1000
moreElimination: 0
weightPrior_factor: 0
initializeMethod: 1
maxJacobianIteration: 15

relativeErrorTolerance: 1e-7
runMode: compare
SA_iteration: 100000
sensorFusionTolerance: 200000
temperatureSA: 100000000
testDataSetName: test_n5_v8
tightEliminate: 0
toleranceEliminator: 1
upperLambda: 1e60
weightLogBarrier: -1.0
setUseFixedLambdaFactor: 1
