%YAML:1.0

# optimization seettings
batchTestMethod: 1 # 1 means NLP, 2 means SA, 0 means initial
testDataSetName: test_n5_v41
AcceptSchedulError: 1e0
debugMode: 1
runMode: compare
initializeMethod: 2
optimizerType: 2 # 1 means dogleg, 2 means LM

deltaOptimizer: 1e-1
exactJacobian: 0
numericalJaobian: 0
#*************************************************************

# Elimination settings
MaxEliminateDetectIterations: 25
stepJacobianIteration: 1.5
ElimnateLoop_Max: 50
toleranceEliminator: 1
tightEliminate: 0
zeroJacobianDetectTol: 1e-7
#*************************************************************

# optimizer settings
deltaInitialDogleg: 1e5
initialLambda: 1e0
lowerLambda: 1e-15
upperLambda: 1e60
relativeErrorTolerance: 1e-5
setUseFixedLambdaFactor: 0
maxIterations: 100
#*************************************************************

# factors to be included
weightDDL_factor: 1.0
makespanWeight: 0
weightPrior_factor: 0
sensorFusionTolerance: 50
FreshTol: 50
withAddedSensorFusionError: 1
#*************************************************************

# task-set settings
coreNumberAva: 5
parallelFactor: 0.4
readTaskMode: orig
TaskSetType: 1 # 1 means total random, 2 means automobile tasksets
timeScaleFactor: 1e0
priorityMode: RM
#*************************************************************

# used in SA
coolingRateSA: 0.1
randomInitialize: 0
temperatureSA: 100000000
SA_iteration: 100000
#*************************************************************


# no need to adjust
noiseModelSigma: 1
saveGraph: 0
#*************************************************************

# not used
barrierBase: 100
punishmentInBarrier: 1e2
weightLogBarrier: -1.0
T: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ 3., 1., 5. ]
#*************************************************************